### ISSUE TITLE
Couldn't find s2v_old folder

### ISSUE THREAD

**Issue by akashjpal** [AOSSIE-Org/EduAid#49]
**Description:**
The issue says it didn't find any s2v_old folder in root directory. This line created the issue in  `backend/Generator/main.py`

 file 
```bash
self.s2v = Sense2Vec().from_disk('s2v_old')
```

**Issue:**
```bash
Traceback (most recent call last):
  File "C:\Users\ASPIRE\Desktop\New folder\EduAid\backend\server.py", line 31, in <module>
    MCQGen = main.MCQGenerator()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASPIRE\Desktop\New folder\EduAid\backend\Generator\main.py", line 34, in __init__
    self.s2v = Sense2Vec().from_disk('s2v_old')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ASPIRE\Desktop\New folder\EduAid\.env\Lib\site-packages\sense2vec\sense2vec.py", line 354, in from_disk
    self.vectors = Vectors().from_disk(path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "spacy\vectors.pyx", line 718, in spacy.vectors.Vectors.from_disk
  File "C:\Users\ASPIRE\Desktop\New folder\EduAid\.env\Lib\site-packages\spacy\util.py", line 1372, in from_disk
    reader(path / key)
  File "spacy\vectors.pyx", line 711, in spacy.vectors.Vectors.from_disk.lambda8
  File "spacy\strings.pyx", line 268, in spacy.strings.StringStore.from_disk
  File "C:\Users\ASPIRE\Desktop\New folder\EduAid\.env\Lib\site-packages\srsly\_json_api.py", line 51, in read_json
    file_path = force_path(path)
                ^^^^^^^^^^^^^^^^
  File "C:\Users\ASPIRE\Desktop\New folder\EduAid\.env\Lib\site-packages\srsly\util.py", line 24, in force_path
    raise ValueError(f"Can't read file: {location}")
ValueError: Can't read file: s2v_old\strings.json
```

**Comment by Roaster05** [comment]
Hey @akashjpal, the error you encountered is due to the missing s2v_old package, which needs to be manually installed in the backend directory. Since we are still in the development phase, we haven't updated the README for our project yet. However, you can check out issue #40 for more details.
