### ISSUE TITLE
[bug] MCQ generation borken

### ISSUE THREAD

**Issue by manthanabc** [AOSSIE-Org/EduAid#85]
# Unexpected response format from backend
mcq generation is currently broken, shows an blank page

## Exact error
```
ERROR
qaPair.answer.filter is not a function
TypeError: qaPair.answer.filter is not a function
    at http://localhost:3000/main.c67f2d856a8237efebf9.hot-update.js:78:41
    at Array.forEach (<anonymous>)
    at http://localhost:3000/main.c67f2d856a8237efebf9.hot-update.js:76:38
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:64502:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:65995:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:65967:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:65957:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:65947:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:67830:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:67783:18)
ERROR
qaPair.answer.filter is not a function
TypeError: qaPair.answer.filter is not a function
    at http://localhost:3000/main.c67f2d856a8237efebf9.hot-update.js:78:41
    at Array.forEach (<anonymous>)
    at http://localhost:3000/main.c67f2d856a8237efebf9.hot-update.js:76:38
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:64502:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:65995:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:65967:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:65957:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:65947:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:67830:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:67783:18)
```

## Expected output
output page should have all the generated questions along with the answer and options, and options to download pdf or export

## Actual output
shows a blank page

## Cause
qaPairs.answer is a type string, while the options are at qaPairs.options, 
This could have happened because someone refactored the backend and forgot to change it in the frontend

**Comment by samriddhi122** [comment]
@manthanabc can  you assign this issue to me

**Comment by manthanabc** [comment]
@samriddhi122  
A. Issues are assigned by maintainers
B. there is already a Pull request for this issue (#86) under review (as you can see linked above)
